[parameters]
#传参没赋值，取不到时默认按这个
#读取excel路径
#生成文件路径
#ta代码，销售商代码，日期

EXCELPATH=.\tmp\申请文件_003销售商_211(1).xls
TXTPATH=./tmp
TACODE=LS
AGENCYNO=
REQDATE=

#图形化界面加载文件类型配置
FILETYPES=01;03;03_1;01_YEB;03_YEB;23;43;43NEW;31;SYJL_026;YF03;52;53;54;55;56;57;59;71;73;X1;X3;R1;NAV;NAVREST;RTT03;GLRYW;GLRMX;GLRZH;GLRQS;SJSMX;SJSFX;GLRXW

#图形化界面加载版本号配置
INTERFACEVERSIONS=20;21;22;12;24;10;211;221;268;270;ZDH



#单个sheet页生成文件时，是否同步加载到数据
roadtodb=0

#余额理财是否合并成一个文件。已废弃，默认不变
yebmerge=0

#生成文件格式，不调整
OUTPUTENCODING=GBK

#使用的数据库链接
dburl=jdbc:oracle:thin:@10.65.137.15:1521:ora19c
dbuser=filedata
dbpwd=filedata
dbdriver=oracle.jdbc.driver.OracleDriver

#覆盖原有加载数据的方式，默认0，0按销售商+日期+版本删除。1按用户号+功能号删除
deletemethod=0

#导出是否分目录
outpathmethon=1
#dblink配置，用于空白文件生成，导出分目录时路径日期查找
dblink=@lsta13

#创表默认前缀，以及数据库导出文件默认查找表的前缀
dbtablepre=lfz_request_

#重排序注释字段标识，将字段替换为如下符号
REDOFLAG=-

#分片大小，无需关注，内存不够用的时候调小
REDOSIZE=50000

#为空不会触发空白文件生成
AUTOBEGINDATE=20211203
AUTOENDDATE=20220310

#tainfo文件拆分成小文件
REDOSPITFILE=1

#比对忽略大小写
ignorecase=1

#是否覆盖原有redo文件，默认1
ISOVERREDO=1

#启动线程，默认空
threadnum=

#导出比对excel是否分目录，预计为1
cproutputmethod=1

#是否开启图形化界面
opengui=0




